version: '3'
services:

  postgres:
    image:
      postgres:10.4
    environment:
      POSTGRES_DB: hiquea
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
